### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/AmplNLReader.jl#19]
Checklist for release.

Anything?

**Comment by dpo** [comment]
There's #13.

**Comment by dpo** [comment]
- [ ] #13 (seems hopeless)
- [ ] https://github.com/JuliaSmoothOptimizers/NLPModels.jl/issues/37

**Comment by dpo** [comment]
I think `develop` can be removed here too?!

**Comment by abelsiqueira** [comment]
I agree

**Comment by dpo** [comment]
Done.

**Comment by dpo** [comment]
I guess this is also getting ready for a release?

**Comment by abelsiqueira** [comment]
I think so, but I don't use or know much AMPL, so it's your decision.

**Comment by dpo** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/11333

**Comment by dpo** [comment]
Done.
