### ISSUE TITLE
Complementarity constraints

### ISSUE THREAD

**Issue by dpo** [JuliaSmoothOptimizers/AmplNLReader.jl#37]
Detect and convey complementarity constraints.

cc: @vepiteski

**Comment by ohinder** [comment]
How difficult is this to do? I was hoping to test my solver on some complementarity problems.

If it is difficult then one hack is I could fairly easily do is write code to change
```
0 <= x[1] complements y[1] >= 0;
```
to

```
x[1] >= 0;
y[1] >= 0;
x[1] * y[1] = 0;
```

in the mod files.

any thoughts?

**Comment by dpo** [comment]
It's ok to change the mod files that way. The disadvantages are that

1. there are other reformulations that you might want to try, e.g., `x[1] * y[1] <= 0`;
2. the information about which constraints are complementarity constraints is lost for solvers that do something special about them.

Ideally, the information should be conveyed from AMPL to the NLPModel. That requires extending the current interface a bit. I don't think it's hard. Someone just needs to find the time to do it.

**Comment by tmigot** [comment]
In ampl/mp they recently added the following pull request:
https://github.com/ampl/mp/pull/112/commits/b6e0d81828cb63c1c5aeebe7ad479b89f8632aad
to extract the "cvar" and "n_cc" used to handle the complementarity constraint on Ampl.

However, not sure where is this information in ASL_jll.jl.

**Comment by dpo** [comment]
It's waiting for a motivated contributor to make a pull request ;-).
