### ISSUE TITLE
Modify Objective Function on Model

### ISSUE THREAD

**Issue by scotthanton** [JuliaSmoothOptimizers/AmplNLReader.jl#39]
Is it possible to modify the objective function of a model after it has been loaded?

**Comment by abelsiqueira** [comment]
I don't think so.
Is it possible to do it directly on the library? (https://github.com/ampl/mp)
Maybe @vepiteski or @dpo can better answer this.

**Comment by dpo** [comment]
Could you explain a bit more what you are trying to do? Everything about the AMPL model is defined and frozen once and for all in the `.nl` file. If you modify only the objective, it won't match the gradient any more and that will throw IPOPT off. If what you're trying to do is create a derived model, you need to define a subtype of `AbstractNLPModel`.

Here's an example. Given a general problem
<p align="center">
minimize <i>f(x)</i>  subject to <i>L ≤ c(x) ≤ U</i>, and <i>l ≤ x ≤ u</i>
</p>
say you want to work with the Tikhonov-regularized problem
<p align="center">
minimize <i>f(x) + &frac12; δ ‖x‖&sup2;</i>  subject to <i>L ≤ c(x) ≤ U</i>, and <i>l ≤ x ≤ u</i>.
</p>

You could use something like the following (untested) definitions:

```julia
type TikhonovModel <: AbstractNLPModel
  meta :: NLPModelMeta
  δ :: Float64
  model :: AbstractNLPModel

  TikhonovModel(model::AbstractNLPModel, δ::Float64) = new(model.meta, δ, model)
end

# define methods specific to TikhonovModel
obj(tmodel::TikhonovModel, x:: AbstractVector) = obj(tmodel.model, x) + 0.5 * tmodel.δ * dot(x, x)

grad(tmodel::TikhonovModel, x:: AbstractVector) = grad(tmodel.model, x) + tmodel.δ * x

function grad!(tmodel::TikhonovModel, x:: AbstractVector, y::AbstractVector)
  grad!(tmodel.model, x, y)
  y[:] += tmodel.δ * x
  return y
end

hess(tmodel::TikhonovModel, x:: AbstractVector; kwargs...) = hess(tmodel.model, x; kwargs...) + tmodel.δ * speye(model.meta.nvar)

# the remaining methods are the same as for the underlying model
for meth in (:cons, :jac_coord, :jac, :cons!, :jprod, :jtprod, :jprod!, :jtprod!)
  @eval $meth(tmodel::TikhonovModel, args...) = $meth(tmodel.model, args...)
end
```
The benefit of this approach is that it will work for any model that derives from `AbstractNLPModel`, not just `AmplModel`s.
