### ISSUE TITLE
prepping for JuliaOpt

### ISSUE THREAD

**Issue by mlubin** [JuliaSmoothOptimizers/AmplNLReader.jl#6]
Continuing the discussion from #4, this package would be a good addition for JuliaOpt. Here's a checklist of what needs to be done:
- [ ] Seamless install using BinDeps
  - [ ] binaries (of asl and ampl.jl wrapper) on OS X
  - [x] binaries (of asl and ampl.jl wrapper) on Windows
  - [x] source build on Linux
- [ ] Register with METADATA

CC @IainNZ @tkelman

**Comment by dpo** [comment]
Sorry I've been so caught up with other stuff. I'd be happy for ampl.jl to be distributed with ampl/mp but I'd like to keep this repo as is as the main development area of Julia/AMPL. Is it possible to pull this repo as a submodule of ampl/mp?

**Comment by tkelman** [comment]
@dpo I think what would be best is factoring things out so any C code wrappers could be contributed to ampl/mp, and all Julia code stays here. That will make managing binaries across all platforms much easier.

**Comment by dpo** [comment]
@tkelman That's a good idea.

@vitaut:
1. An easy way to install `ampl.jl` is with Homebrew. Would it be better to change the [`asl.rb` Homebrew formula](https://github.com/Homebrew/homebrew-science/blob/master/asl.rb) to pull your releases instead of Dave's who are never versioned (and cause infinite trouble)? Homebrew bottles the ASL, and so precompiled binaries are available for OSX (and soon for Linux). On Windows, I'm not sure what to do.
2. How should I migrate the C wrapper to ampl/mp? Submit a PR?

**Comment by tkelman** [comment]
> Would it be better to change the asl.rb Homebrew formula to pull your releases instead of Dave's who are never versioned (and cause infinite trouble)? 

+1

>  On Windows, I'm not sure what to do.

I got it covered. https://build.opensuse.org/package/show/home:kelman:mingw-coinor/mingw64-ampl-mp will allow us to use WinRPM.

**Comment by vitaut** [comment]
@dpo Thanks for relicensing the code.

> 1. Would it be better to change the asl.rb Homebrew formula to pull your releases instead of Dave's who are never versioned (and cause infinite trouble)? 

Sounds good. The ASL in ampl/mp repo is regularly updated, so there shouldn't be any difference apart from new the versioning.

> 2. How should I migrate the C wrapper to ampl/mp? Submit a PR?

PR would be great. Alternatively, I can add this repo as an optional submodule of ampl/mp as it is done with other [modules](https://github.com/ampl/mp#modules) like gsl or gecode.

**Comment by mlubin** [comment]
I have nothing to contribute at the moment, but happy to see things moving along!

**Comment by tkelman** [comment]
Thanks for going through with the PR @dpo, and for merging it @vitaut. Is the code in the upstream repository usable by the Julia package yet? Assuming a near-future release gets tagged when ready with the new code in roughly the state it's in today?

Also for clarity I think this package will probably need a slightly more specific name. Maybe `AmplEvaluator` or something? Since in addition to this package we will also have an `AmplMathProgInterface`, and an `AmplNlWriter` (or similar), all serving slightly different purposes and with slightly different dependency directions.

**Comment by dpo** [comment]
@tkelman When @vitaut is ready to make a new release with the interface built into the shared lib, I'll be able to test.

We'll need the Homebrew formula for `asl` to be accepted in `Homebrew.jl`. Once that's done, writing a `build.jl` shouldn't be too difficult.

Regarding the name, how about `AmplModel`? That's already the name of the main type actually.

**Comment by tkelman** [comment]
Can you test on master to see if there are any issues ahead of time? Or does it still need work to build into the shared lib?

This package can only import and evaluate functions from a model that's been previously created elsewhere, right? So this isn't creating models straight from mathematical formulations quite like JuMP/Convex do, it's primarily importing models that are created in AMPL? Or is there the capability here of populating an AMPL model entirely from Julia code?

**Comment by dpo** [comment]
The build system still needs work to build the shared lib.

No, this package doesn't create AMPL `mod` and `dat` files. It imports `nl` files and provides a convenient interface. Maybe `AmplNlReader` is better then?

**Comment by mlubin** [comment]
``AmplNlReader`` (or ``AmplNLReader``?) sounds good to me. This will fit in with the ecosystem of AMPL-related packages that will soon be published and also makes it more clear that the package is not a replacement for AMPL.

**Comment by dpo** [comment]
The [`feature/libasl`](https://github.com/dpo/ampl.jl/tree/feature/libasl) branch prepares for the external library. There is a tentative [`build.jl`](https://github.com/dpo/ampl.jl/blob/feature/libasl/deps/build.jl) that builds from source or picks up the libraries build via Homebrew. For now the OSX build fails on Travis because `libasl` doesn't yet include the new interface, and the Linux build fails because Ubuntu 12.04 has an outdated `cmake`.

**Comment by dpo** [comment]
I updated `build.jl` to build the latest `libasl`, but it seems it's not being detected. The odd thing is that if I `brew install asl`, then the version previously installed by BinDeps *is* detected. Anything seems wrong in `build.jl`?

**Comment by tkelman** [comment]
Looks like it should work, not sure? Try adding a `dlopen` of the dylib, see if there's an error message?

The `[:libasl => :libasl]` will give a deprecation warning that can be avoided with the Compat.jl package via `@compat @BinDeps.install Dict(:libasl => :libasl)`, that will let you use the `deps.jl` cached file to avoid requiring BinDeps at runtime - it's only necessary for `Pkg.build`, not `using` the package.

**Comment by mlubin** [comment]
``libasl.so`` doesn't properly specify a dependency on libmp:
```
ERROR: could not load module /home/mlubin/.julia/v0.3/ampl/deps/usr/lib/libasl.so: libmp.so.1: cannot open shared object file: No such file or directory
 in dlopen at c.jl:19
```
also ``ldd -r libasl.so`` lists tons of missing symbols. 

CC @vitaut

**Comment by mlubin** [comment]
Okay, there is a dependency on ``libmp.so.1`` but without a path. So this would work if ``LD_LIBRARY_PATH`` was set, although this shouldn't be needed at all.

**Comment by dpo** [comment]
I removed the `[:libasl => :libasl]` altogether. I suppose there's no harm in also exporting `libmp`. And `ampl.jl` now `include`s `deps.jl`. Is that what you meant?

On OSX, I get
````
$ otool -L ~/.julia/v0.3/ampl/deps/usr/lib/libasl.dylib
/Users/dpo/.julia/v0.3/ampl/deps/usr/lib/libasl.dylib:
	@rpath/libasl.1.dylib (compatibility version 1.0.0, current version 1.4.0)
	@rpath/libmp.1.dylib (compatibility version 1.0.0, current version 1.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
````
Perhaps `-rpath` wasn't specified when building the dynamic lib?!

**Comment by vitaut** [comment]
@mlubin Sorry, forgot to update the so versions which could cause missing symbols if wrong version of the library is picked up. Fixed in https://github.com/ampl/mp/releases/tag/2.0.1. I'll have a look why `libmp` dependency is not working. Probably need to set rpath or something.

**Comment by dpo** [comment]
@vitaut I'm still having the same issue.

**Comment by vitaut** [comment]
@dpo If you mean the dependency issue, then I haven't looked into it yet. A trivial workaround is to link with both `libasl` and `libmp`.

**Comment by mlubin** [comment]
There could be a way to force BinDeps to load ``libmp`` before ``libasl``, wasn't able to figure it out though.

**Comment by vitaut** [comment]
According to [CMake RPATH handling](http://www.cmake.org/Wiki/CMake_RPATH_handling), CMake clears the RPATH when installing targets. So `libasl.so` will find `libmp.so` if it is installed in one of the standard library directories (tested on Linux). Feel free to submit an issue or a PR to [AMPL/MP](https://github.com/ampl/mp) if you want it to be found in non-standard locations.

**Comment by tkelman** [comment]
Might help if we try manually setting `-DCMAKE_INSTALL_RPATH=$prefix/lib` ?

**Comment by mlubin** [comment]
So compilation from source via BinDeps is working now. @tkelman, is asl already in opensuse?

**Comment by tkelman** [comment]
Yes - https://build.opensuse.org/package/show/windows:mingw:win64/mingw64-ampl-mp @vitaut you may want to have a look at a patch the opensuse guys added, I think they bumped to gcc 5.1.0 and that may have introduced a problem that they added a patch to fix. I'll try to see if I can reproduce the issue at some point.

It looks like there's a dependency now on an unregistered "NLP.jl" package, which I don't think is appropriately named, nor does it actually contain enough information to actually be fully useful. It looks like it's just storing counts of variables and different types of constraints, but if this package and CUTEst.jl both want to use the same data structure I think the type could probably be added to MathProgBase?

**Comment by dpo** [comment]
The idea is to merge whatever's in `NLP.jl` that isn't already in `MathProgBase` into `MathProgBase` when it's ready. Currently, `NLP.jl` helps me experiment with modifying optimization problems in place.

**Comment by mlubin** [comment]
Almost all of the information in the NLP.jl structure is available through the MathProgBase nonlinear interface, but perhaps in a less convenient form for using it to transform problems when writing a solver. I'd like to see some convergence between the two interfaces, but as a short-term solution I think it would be okay to just move the data structure into ``MathProgBase``. This would let us move forward with registering this package and moving it into JuliaOpt, that is, if you (@dpo) believe that the package is ready.

**Comment by dpo** [comment]
@mlubin Sure that sounds good to me. I think `ampl.jl` is in good shape and I'd like to consolidate everything as well.

**Comment by vitaut** [comment]
@tkelman The issue with GCC 5 is fixed in https://github.com/ampl/mp/commit/40c1f7fbf4a1647c6fadb9969343a68d244b8e48, thanks!

**Comment by mlubin** [comment]
@dpo, ready to go ahead with this? The next steps are to rename the package to ``AmplNLReader`` (as discussed) and publish what's in the develop branch in metadata.

**Comment by tkelman** [comment]
And uncomment the WinRPM lines in `deps/build.jl` (the package on opensuse is named `"ampl-mp"`, not `"asl"` though), add `@windows WinRPM` to `REQUIRE`, and turn on appveyor

**Comment by dpo** [comment]
Almost there. Any idea why this would fail on win32 and nowhere else?
https://ci.appveyor.com/project/dpo/amplnlreader-jl/build/1.0.4/job/jrdgtr5bp8vf3b8d#L62

**Comment by tkelman** [comment]
Integer literals being 32 bit there, probably. Would likely also fail on 32 bit Linux but that's kinda tricky to get working on Travis.
```
ERROR: `convert` has no method matching convert(::Type{Array{Int64,1}}, ::UnitRange{Int32})
 in NLPModelMeta at C:\Users\appveyor\.julia\v0.3\MathProgBase\src\NLP\nlp_types.jl:108
 in AmplModel at C:\Users\appveyor\.julia\v0.3\AmplNLReader\src\AmplNLReader.jl:74
```

**Comment by dpo** [comment]
We changed `Int64` to `Int` everywhere in `NLP.jl`, but still have the same error. Does `MathProgBase` need to be updated in `META` in order for the change to be taken into account?!

**Comment by dpo** [comment]
ps @tkelman sorry I missed your talk today at ISMP.

**Comment by tkelman** [comment]
No worries, many many tracks. I'll probably post my slides somewhere, likely https://github.com/tkelman/ISMP2015

So yes we need MathProgBase to get tagged to reflect the latest Int64 to Int changes, though as a temporary testing measure we could also add `Pkg.checkout("MathProgBase")` somewhere in the `appveyor.yml` file.

**Comment by mlubin** [comment]
MPB is tagged now

**Comment by dpo** [comment]
e92396dff8dc1a6ce138cae1dadfa26935dc6e6f implements error code checking. Now we're waiting for a new release of ampl/mp but there are issues pending there. Temporarily, I [patched](309c80ac6e72d398ffad1c113ec5045b9cb15b9c) the updated generic interface into the current release. It's working well on OSX, Linux and Windows.

**Comment by mlubin** [comment]
Bump. Anything else holding up registering the package in METADATA?

**Comment by dpo** [comment]
https://github.com/ampl/mp/commit/5066e70e59d5640f78a19e985a0863f030b872fc didn't make it into release 2.0.2 apparently. Is it acceptable to register with the patch?

**Comment by mlubin** [comment]
Yes, I'd say so.

**Comment by dpo** [comment]
Actually it's a problem because the binaries are off (both Homebrew and windows RPM).

**Comment by mlubin** [comment]
Oh, I see that the signatures of the functions have changed. Yes, that's an issue.

**Comment by tkelman** [comment]
I can update the WinRPM binary (technically anyone with an opensuse build service account can submit an update request, it works a bit like github PR's), patches are okay there - just let me know exactly what it needs. Should we wait to see what happens on https://github.com/ampl/mp/issues/64 first?

**Comment by dpo** [comment]
Yes, let's see what happens. Thanks.

**Comment by mlubin** [comment]
I think it's safe to close this now that the organizations have settled down.
