### ISSUE TITLE
Limit NLPModels version, drop 0.7, add 1.1 support, make minor release

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/AmplNLReader.jl#61]
- [ ] Limit NLPModels version in current version, since it doesn't handle structure updates;
- [ ] Drop 0.7 support and add 1.1 support;
- [ ] Make a new release.

**Comment by dpo** [comment]
#64 adds support for structure. Would be great to tick the last two boxes now.

**Comment by dpo** [comment]
I think this can be closed.
